# Generated by Django 5.0.3 on 2024-04-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='place',
            new_name='province',
        ),
    ]
