# Generated by Django 5.0.3 on 2024-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invocie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invocie',
            new_name='Item',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
